# Write your MySQL query statement below
SELECT A1.machine_id, ROUND(AVG(A2.timestamp-A1.timestamp),3) AS "processing_time"
FROM ACTIVITY A1
INNER JOIN ACTIVITY A2
ON A1.MACHINE_ID=A2.MACHINE_ID AND A1.PROCESS_ID=A2.PROCESS_ID
WHERE A2.ACTIVITY_TYPE="END" AND A1.ACTIVITY_TYPE="START"
GROUP BY A1.MACHINE_ID;